### ISSUE TITLE
Details about implementation

### ISSUE THREAD

**Issue by cyrusmsk** [ronnie-w/webviewd#1]
Probably it will be helpful to have some more detail about implementation in the Readme.

If ImportC was used? Or if bindings generated automatically/manually?
How this library is different from others:
- https://code.dlang.org/packages/webview
- https://code.dlang.org/packages/guino

**Comment by ronnie-w** [comment]
It just includes converted webview.h to webview.d by [dstep](https://github.com/jacob-carlborg/dstep), webview source files and pre-build commands. With [webview](https://github.com/thechampagne/webview-d), you'll need to prebuild webview then link the object files or shared libs yourself. What this package does is build the the object files and link them for you.

**Comment by ronnie-w** [comment]
Will include it in the readme.
